# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "126c58a33787e04dcbbdb60f2b2ac4d1"
name = "cru"
handle = "cru"
application_url = "https://mba-kinda-mainstream-rally.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-c0eb237e.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://mba-kinda-mainstream-rally.trycloudflare.com/auth/callback",
  "https://mba-kinda-mainstream-rally.trycloudflare.com/auth/shopify/callback",
  "https://mba-kinda-mainstream-rally.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
